# Generated by Django 5.2.5 on 2025-08-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('vehiculo', models.CharField(blank=True, max_length=80)),
                ('patente', models.CharField(blank=True, max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('ubic_lat', models.FloatField(blank=True, null=True)),
                ('ubic_lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'choferes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idoped', models.AutoField(primary_key=True, serialize=False)),
                ('fecped', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('notped', models.TextField(blank=True, null=True)),
                ('estped', models.CharField(choices=[('PEN', 'Pendiente'), ('ENV', 'En ruta'), ('ENT', 'Entregado')], default='PEN', max_length=10)),
                ('totped', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('asignado_at', models.DateTimeField(blank=True, null=True)),
                ('entregado_at', models.DateTimeField(blank=True, null=True)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos.chofer')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.cliente')),
            ],
            options={
                'db_table': 'pedidos',
                'ordering': ['-fecped', '-hora'],
            },
        ),
    ]
