# Generated by Django 5.2.5 on 2025-08-15 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nota_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estped',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('ENV', 'En ruta'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], default='PEN', max_length=10),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(default='Disponible', max_length=50)),
                ('chofer_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='pedidos.chofer')),
            ],
            options={
                'db_table': 'vehiculos',
                'ordering': ['tipo', 'patente'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos.vehiculo'),
        ),
    ]
