# Generated by Django 5.2.5 on 2025-08-15 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_categoria_pedido_nota_entrega_pedido_urgente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['marca', 'modelo']},
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='estado',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='chofer_asignado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo_asignado', to='pedidos.chofer'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
